# applies to podtato-head-entry deployment only
ingress:
  className: nginx
  annotations:
    dns.gardener.cloud/class: garden
    dns.gardener.cloud/dnsnames: dekra-johnny-test.demo-dekra.kubrix.cloud
    dns.gardener.cloud/ttl: "180"
  hosts:
    - host: dekra-johnny-test.demo-dekra.kubrix.cloud
      paths:
        - path: /
          pathType: ImplementationSpecific
